
    <!-- footer START -->
    <div id="footer"> <a id="gotop" href="#" onclick="MGJS.goTop();return false;">Go Top</a>
      <div id="copyright"> MM Movie </div>
      
    </div>
    
    <!-- footer END --> 
    
  </div>
  <!-- container END --> 
</div>
<!-- wrap END --> 

<!-- Dynamic page generated in 0.493 seconds. --> 
<!-- Cached page generated by WP-Super-Cache on 2011-04-01 22:29:55 --> 
<!-- super cache -->
</body>
</html>